#!/usr/bin/env bash
# This script modifies /etc/hosts to map localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Backup current hosts file
cp /etc/hosts /etc/hosts.bak

# Remove existing localhost and facebook.com entries
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

# Add the new entries
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts